### ISSUE TITLE
Output data as `pandas.DataFrames` and `Series`

### ISSUE THREAD

**Issue by sharkweek** [lasso-gmbh/lasso-python#10] opened 2020-09-24 17:26 UTC
I'm working with composite shells and output individual integration point (i.e. ply) strains to `eloudet` in the `binout`. For some reason, though, when I try to read the data using `binout.read('eloutdet', 'shell', 'eps_xx')`, it exports as a 1D array of tuples which causes problems for direct import into `pandas.DataFrame`s. I assume this is because of some dimensional limit in a `numpy.ndarray`. Would it be possible to retool so that the data is instead exported natively as a `pandas.DataFrame` or `Series`?

**Comment by lasso-codie** [comment] 2020-09-24 17:56
The idea is great, I'm just not sure if there is a generic way of conversion. How do you currently convert your data to pandas? Also it is odd that you get an array of tuple. Before returning data I call `np.asarray`, which should convert everything, including these tuples.

**Comment by sharkweek** [comment] 2020-09-24 19:41
I also tried `np.asarray()`, but with the same result. Currently, I have to convert the `Binout.read()` output to a list and _then_ to a `pandas.DataFrame` like this:

```python
>>> binout = Binout('binout')
>>> df_eps_xx = pd.DataFrame(binout.read('eloutdet', 'shell', 'eps_xx')).tolist())
>>> df_eps_xx.head()
     0    1    2    3    4    5    6    7    8    9
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
```

The problem with this, however, is twofold: first, the way this is implemented by `Binout.py` produces a deprication warning from `numpy`, so who knows how much longer this method will work. Second, for the data to be readable, either the columns need to be renamed (they are imported as just the indices of the tuples), or passed to an existing `DataFrame` with the appropriate column names. As you can imagine, this can get quite cumbersome if you are trying to look at data in multiple directions (e.g. _xx_ vs _yy_ vs _zz_).

In general, I imagine most people will be assessing the `binout` data with respect to time steps, so it makes sense that the output would be some sort of `DataFrame` subclass indexed by the `time` field. The subclass would then have the other attributes  like `system` and `title` that could easily be accessed.

**Comment by sharkweek** [comment] 2020-09-24 19:45
I forgot to mention that this behavior is not universal across all `binout` types. For example, reading hourglass energy by part from `matsum` results in a proper `numpy.ndarray`.

```python
>>> binout.read('matsum', 'hourglass_energy')
array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.54519884e-27],
       [0.00000000e+00, 0.00000000e+00, 3.09221398e-27],
       ...,
       [8.13865335e+01, 1.44629312e+03, 3.24694676e+03],
       [8.14288573e+01, 1.44670708e+03, 3.24842920e+03],
       [8.14699180e+01, 1.44711480e+03, 3.23677619e+03]])
```

**Comment by lasso-codie** [comment] 2020-09-25 08:35
> 
> 
> I also tried `np.asarray()`, but with the same result. Currently, I have to convert the `Binout.read()` output to a list and _then_ to a `pandas.DataFrame` like this:
> 
> ```python
> >>> binout = Binout('binout')
> >>> df_eps_xx = pd.DataFrame(binout.read('eloutdet', 'shell', 'eps_xx')).tolist())
> >>> df_eps_xx.head()
>      0    1    2    3    4    5    6    7    8    9
> 0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
> 1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
> 2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
> 3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
> 4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
> ```
> 
> The problem with this, however, is twofold: first, the way this is implemented by `Binout.py` produces a deprication warning from `numpy`, so who knows how much longer this method will work. Second, for the data to be readable, either the columns need to be renamed (they are imported as just the indices of the tuples), or passed to an existing `DataFrame` with the appropriate column names. As you can imagine, this can get quite cumbersome if you are trying to look at data in multiple directions (e.g. _xx_ vs _yy_ vs _zz_).
> 
> In general, I imagine most people will be assessing the `binout` data with respect to time steps, so it makes sense that the output would be some sort of `DataFrame` subclass indexed by the `time` field. The subclass would then have the other attributes like `system` and `title` that could easily be accessed.

Good idea in general.

For multi-dimensional tensors with logically ndim > 3 wouldn't it make more sense to reshape into tensors with named dimensions instead of keeping everything flattened? But yeah the issue is, that there is no generic way obtaining dimension or column names, but for the moment this can be left to the user (the file format does not contain any information about tensor dimensions or names). 

Most data is indeed timestamped, though there are dataseries without time (broke my code in the past). They are rare but it occurs. I need to look up what it was last time I encountered it. I'm not sure yet how to handle these. Nonetheless I think a conversion to DataFrames as you described still makes sense,

Regarding the conversion to numpy array, I'm quite surprised that sometimes it works and sometimes not. Numpy should convert everything including nested tuples. I really wonder what is happening internally that the conversion fails.

**Comment by sharkweek** [comment] 2020-11-24 15:40
I thought about this a bit, and at first, I thought that you could just assume that any data having the same first dimension as `time` would be a `DataFrame`. Unfortunately, this will likely cause problems if you use different `dt` values in each of your `*DATABASE` requests.

Instead, I think the best way to handle it may be to create a method similar to `asarray()` in `numpy` that will cast the data as a `DataFrame`. The other option is to add a boolean argument like `timeseries` or something that will cause the data to be returned as a `DataFrame` indexed by time.

**Comment by lasso-codie** [comment] 2020-12-10 14:30
How about a method or argument `as_df` to convert it?

**Comment by sharkweek** [comment] 2020-12-10 18:27
Both ideas sound great. I'm not too familiar with the underlying architecture, so I'm not sure which would be easier. I imagine a separate method might be the best for building out new options, though. It would look similar to the `read()` method and accept subdirectories in the `binout`, except it would also a list of subdirectories for the dataframe columns. Something like this:

```python
binout.as_df('glstat', ['hourglass_energy', 'total_energy'])
binout.as_df('glsta', 'all')
```

The trickier part would be for more complex outputs like `matsum` or `nodfor` that also have individual part/element/node IDs. Maybe something like this:

```python
binout.as_df('matsum', ['x_rbvelocity', 'y_rbvelocity'], ids=[1, 3, 10])
```

I'm not sure what the best structure for the result for this would be, though. It could either return a single, multi-indexed dataframe by entity ID, a single, giant data frame with an entity ID column, or a separate dataframe for each ID.

**Comment by sharkweek** [comment] 2021-01-07 17:12
How about something like this in the `Binout` class?

```python
    def as_df(self, *args):
        """Return data as a pandas DataFrame."""

        data = self.read(*args)

        # validate time-based data
        if type(data) != np.ndarray:
            raise ValueError("Not a time-based data")
        elif data.shape[0] != self.read(args[0], 'time').shape[0]:
            raise ValueError("Not a time-based data")
        else:
            time = pd.Index(self.read(args[0], 'time'), name='time')

        # create dataframe
        if data.ndim > 1:
            df = pd.DataFrame(index=time)
            for i, j in enumerate(self.read(args[0], 'ids')):
                df[str(j)] = data.T[i]
        else:
            df = pd.Series(data, index=time, name=args[-1])

        return df
```

**Comment by lasso-codie** [comment] 2021-01-08 09:08
Thanks for the contribution and good job 👍 I altered it slightly and added it to the code:
- slight alteration in error checking logic
- when fetching time and ids we need to take args except last one since depth can be higher than two

```python
def as _df(self, *args) -> 
        data = self.read(*args)

        # validate time-based data
        if not isinstance(data, np.ndarray):
            err_msg = "data is not a numpy array but has type '{0}'"
            raise ValueError(err_msg.format(type(data)))

        time_array = self.read(*args[:-1], 'time')
        if data.shape[0] != time_array.shape[0]:
            raise ValueError("data series length does not match time array length")

        time_pdi = pd.Index(time_array, name='time')

        # create dataframe
        if data.ndim > 1:
            df = pd.DataFrame(index=time_pdi)
            ids = self.read(*args[:-1], 'ids')
            for i, j in enumerate(ids):
                df[str(j)] = data.T[i]
        else:
            df = pd.Series(data, index=time_pdi, name=args[-1])

        return df
```

I will close the issue then but I have the feeling there is still room for improvement.

**Closed by lasso-codie** 2021-01-08 09:08 UTC

**Comment by sharkweek** [comment] 2021-01-11 23:34
That's perfect! I'll try taking it for a spin!

**Comment by sharkweek** [comment] 2021-01-19 14:53
I just discovered an issue with this method when using contact force data in `rcforc`. It appears that the `read()` method reads in the `ids` as an integer array by `*CONTACT` ID and makes no distinction between the master and slave contact entities.

```python
# a run with three `*CONTACT* cards
>>> binout.read('rcforc', 'x_force')
array([1, 1, 2, 2, 3, 3])
```

Running `as_df` for `rcforc` seems to only take one of the fields represented by each unique integer. I suggest replacing the line where the IDs are determined with something like the following:

```python
if args[0] == 'rcforc':
    ms = ['m' if (i % 2) else 's'
          for i, j in enumerate(self.read('rcforc', 'ids'))]
    ids = [str(i) + str(j) for i, j in zip(self.read('rcforc', 'ids'), ms)]
else:
    ids = self.read(*args[:-1], 'ids')
```

This should produce something like this:

```python
['1s', '1m', '2s', '2m', '3s', '3m']
```
