### ISSUE TITLE
Issue with strains and stresses state when using DCOMP=2 in *DATABASE_EXTENT_BINARY

### ISSUE THREAD

**Issue by Martal24** [lasso-gmbh/lasso-python#1] opened 2019-10-04 17:13 UTC
Hi !
Thanks for this great library !
I've encountered a bug as i was testing this library. For some of my d3plot file I can't read strains and stresses values. I think it is linked with my use of data compression (DCOMP=2)

I've tried to isolate the bug and I think there is a problem with the condition 
``
if self.header["nel4"] <= 0 \
or self.header["nv2d"]-self.header["numrbe"] <= 0:
return var_index
``
At the beginning of `_read_states_shell` in `D3plot.py`. I don't completely understand what is check there, but when I comment those lines, everything seems to work fine.

If I got the time, I will look deeper into it next week.

Thanks again for your time,
Rémi Lafarge

**Comment by lasso-codie** [comment] 2019-10-04 20:30
I see the bug directly 😅 The issue is, that the state array has the length `nel4` (number of shells) minus the number of rigid shell elements `numrbe`, which will not output any state data. Seems I messed up the security check. Glad it works then though.

**Comment by lasso-codie** [comment] 2019-10-05 17:50
@Martal24 can you maybe send me an example file for testing? Dont want to make a fix without an example file.

**Comment by lasso-codie** [comment] 2019-10-10 18:16
Kk will do a blind fix then.

**Comment by lasso-codie** [comment] 2019-10-11 07:37
Fixed, it will be included in the next release.

**Closed by lasso-codie** 2019-10-11 07:37 UTC
Labels: bug
