### ISSUE TITLE
problem reading large number of d3plot files

### ISSUE THREAD

**Issue by jmaestre2** [lasso-gmbh/lasso-python#4] opened 2020-03-28 09:03 UTC
Hello,

Firstly let me thanks you for this great python library.

I am using this library in my project to read the results of big simulations.
Basically I found a bug reading d3plot files. When the simulation is big, I cannot read all the d3plot files at once and I should read them one by one or for blocks (D3plot(patchTofile,False,1,["timesteps","element_solid_stress'])). The problem arises when the number of d3plot files is larger than 100 files. Then, when it is reading the the i_state 100, instate of saving the data in the array at the corresponding position, it rewrites the position 10. That happens recurrently for the position 200 and 300, etc.
The problem can be detected easily if you see the timesteps arrays. You can see the position 10 of that array is wrong.

I hope you can fix the bug

Ciao,
Jorge

**Comment by lasso-codie** [comment] 2020-03-28 11:13
Hey Jorge,
thanks for reporting, sounds like a memory transfer issue. Will check it out.

**Comment by jmaestre2** [comment] 2020-03-28 13:27
Thanks to you for this great tool. Please, let me know if you find the bug.

Ciao
Jorge

**Comment by jmaestre2** [comment] 2020-03-28 19:30
Hello,

I think I found the bug. It is not the memory transfer. Basically, after load the i_state 10, it load the i_state 100 (function :   self._read_d3plot_file_generator(filepath, n_files_to_load_at_once) ). 

Specifically, I think the issue is related to the sort of the filepaths. The sort is wrong. Function ''filepaths = D3plot._find_dyna_result_files(base_filepath)''. 

I hope this clue help you to find and fix the issue.

**Comment by lasso-codie** [comment] 2020-03-28 20:33
thanks should be pretty simple to fix!

**Comment by lasso-codie** [comment] 2020-04-01 07:52
@jmaestre2 hmmm I cannot reproduce. How is the naming pattern for going beyond 100? Is it all zero-padded such as d3plot001, d3plot002, ..., d3plot100?

**Comment by jmaestre2** [comment] 2020-04-02 20:06
Hello,

The pattern is d3plot01,
d3plot02,..d3plot10,d3plot11,...d3plot100,d3plot101.
When it is sorted the sequence is like d3plot09,d3plot10,d3plot100,.

I fixed the bug defining a natural sorting key for the function "sorted".
This is:
        convert = lambda text: int(text) if text.isdigit() else
text.lower()
        alphanum_key = lambda key: [ convert(c) for c in
re.split('([0-9]+)', key) ]

        return sorted(filepaths,key = alphanum_key)

Thanks a lot!!
Jorge

**Comment by lasso-codie** [comment] 2020-04-06 11:14
Gj and thanks. It's an easy fix then, will add a test and alphasort 👍

**Comment by lasso-codie** [comment] 2020-04-14 08:01
Will be in the next release

**Closed by lasso-codie** 2020-04-14 08:01 UTC
Labels: bug
